const menus={
'Học sinh':['Bài tập cần làm','Kết quả học tập','Tài liệu học tập','Lộ trình & lịch','Trò chơi','Cửa hàng thường','Cửa hàng sang trọng','Phần thưởng','Kho vật phẩm','Bảng xếp hạng','Hộp thư & khảo sát','Lịch sử giao dịch','Cài đặt'],
'Giáo viên':['Giao bài tập','Bài tập đã giao','Bài đã nộp','Tài liệu học tập','Quản lý học sinh','Lộ trình & lịch','Quản lý trò chơi','Ngân hàng câu hỏi','Quản lý phần thưởng','Thông báo & khảo sát','Giao dịch & yêu cầu','Kháng cáo','Cài đặt'],
'Đăng nhập':['Đăng nhập'],
'Bộ giao diện':['Màu & thành phần','Thông báo & trạng thái','Chuyển động']};
const icons=['▤','▥','▧','◇','♧','▦','✧','♜','▣','♕','✉','↔','⚙'];let role='Học sinh',active=menus[role][0];
const btn=(s,cls='primary')=>`<button class="${cls}" data-dialog="${s}">${s}</button>`;
const card=(s)=>`<article class="card">${s}</article>`;
const stats=(items)=>`<div class="stats">${items.map(([l,v,t])=>card(`<div class="stat"><span>${l}</span><strong>${v}</strong><em>${t||'Dữ liệu minh họa'}</em></div>`)).join('')}</div>`;
const table=(heads,rows)=>card(`<div class="tablewrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);
const toolbar=(placeholder='Tìm kiếm...')=>`<div class="toolbar"><input placeholder="${placeholder}" aria-label="Tìm kiếm"><select aria-label="Lọc"><option>Tất cả</option><option>Đang mở</option><option>Đã hoàn tất</option></select>${btn('Bộ lọc','')}</div>`;
const tabs=(a)=>`<div class="tabs">${a.map((x,i)=>`<button class="${i?'':'active'}" data-tab>${x}</button>`).join('')}</div>`;
function content(){
if(active==='Đăng nhập')return `<div class="login card"><span class="badge">CHÀO MỪNG TRỞ LẠI</span><h1 style="margin-top:18px">Bắt đầu một ngày<br>học tập mới.</h1><p class="muted">Đăng nhập vào không gian của bạn.</p><label>Tên đăng nhập<input placeholder="Nhập tên đăng nhập"></label><label>Mật khẩu<input type="password" placeholder="Nhập mật khẩu"></label>${btn('Đăng nhập')}<p class="muted" style="font-size:12px;margin-top:20px">Cần trợ giúp? Liên hệ giáo viên của bạn.</p></div>`;
if(active==='Màu & thành phần')return `<p class="subtitle">Một bộ màu dùng xuyên suốt đăng nhập, học sinh, giáo viên và hộp thoại.</p><div class="grid">${[['Chủ đạo','#5559dc'],['Nền trang','#f5f6fb'],['Chữ chính / menu','#202d49'],['Nền thẻ','#ffffff'],['Thành công','#197b60'],['Lỗi / xóa','#bc3e54']].map(([n,c])=>card(`<div class="swatch" style="background:${c};border:1px solid #e3e7f1"></div><b>${n}</b><small>${c}</small>`)).join('')}</div>${card(`<h2>Nút và trạng thái</h2><div class="toolbar">${btn('Thao tác chính')}${btn('Thao tác phụ','')}${btn('Xóa dữ liệu','danger')}<button disabled>Chưa đủ điều kiện</button></div><span class="badge success">Đã hoàn thành</span> <span class="badge warning">Đang chờ</span><p class="muted" style="margin-top:20px">Chỉ dùng màu vàng cho Coin và cảnh báo; màu đỏ cho lỗi, xóa. Vật phẩm có chủ đề riêng giữ ảnh và màu nhận diện của chúng.</p>`)}`;
if(active==='Thông báo & trạng thái')return `<div class="grid">${card(`<h2>Thông báo ở giữa</h2><p class="muted">Cùng kiểu chữ, màu nút và khoảng cách trên mọi trang.</p>${btn('Thử thông báo')}`)}${card(`<h2>Xác nhận thao tác</h2><p class="muted">Nút Hủy trung tính, hành động chính rõ ràng.</p>${btn('Thử xác nhận xóa','danger')}`)}${card(`<h2>Đang tải</h2><div class="skeleton"></div><div class="skeleton" style="width:65%"></div><small>Hiển thị khung nội dung trước khi tải xong.</small>`)}${card(`<div class="empty"><h2>Chưa có dữ liệu</h2><p class="muted">Khi có bài tập mới, nội dung sẽ xuất hiện tại đây.</p>${btn('Tải lại','')}</div>`)}${card(`<span class="badge warning">Mất kết nối</span><h2 style="margin-top:16px">Chưa xác nhận hoàn tất</h2><p class="muted">Giữ lại nội dung đã nhập và cho phép kiểm tra lại.</p>${btn('Kiểm tra / thử lại')}`)}</div>`;
if(active==='Chuyển động')return `${card(`<span class="badge">CHUYỂN ĐỘNG CÓ THỂ THỬ NGAY</span><h2 style="margin-top:16px">Nhẹ, rõ, nhất quán.</h2><p>Chuyển mục: nội dung hiện dần trong 350 ms. Thẻ hiện lệch nhau 60 ms. Nút nổi nhẹ khi rê chuột, nhấn xuống khi bấm. Hộp thoại mở trong 240 ms.</p><div class="toolbar"><button id="replay" class="primary">Phát lại hiệu ứng</button>${btn('Thử mở hộp thoại')}</div><p class="muted">Không dùng chuyển động nền liên tục che chữ. Tôn trọng thiết lập giảm chuyển động của thiết bị; chế độ tối ưu chỉ giảm hiệu ứng trang trí.</p>`)}<div class="grid">${[1,2,3].map(i=>card(`<span class="badge">${i<10?'0':''}${i}</span><h2 style="margin-top:16px">Thẻ xuất hiện ${i}</h2><div class="progress"><b></b></div>`)).join('')}</div>`;
if(active==='Cài đặt')return card(`<h2>Giao diện & trải nghiệm</h2>${[['Màu giao diện','Mặc định · Xanh chàm thống nhất'],['Chuyển động giao diện','Chuyển trang, phản hồi nút, mở hộp thoại'],['Hiệu ứng vật phẩm','Điều chỉnh độc lập với chuyển động giao diện'],['Tối ưu hiệu năng','Tải nội dung khi cần, giảm hiệu ứng nền nặng'],['Lớp kính nội dung','Dành cho nền đặc biệt đang sử dụng'],['Hướng dẫn chi tiết','Xem hướng dẫn và thử bằng mô phỏng'],['Tài khoản & bảo mật','Tên hiển thị và đổi mật khẩu']].map(([a,b])=>`<div class="setting"><div><b>${a}</b><p>${b}</p></div>${btn('Thiết lập','')}</div>`).join('')}`);
if(active.includes('Cửa hàng')||active==='Phần thưởng'||active==='Kho vật phẩm')return `${stats([['Số dư Coin','8.500','Dùng để mua vật phẩm'],['Đã sở hữu','12 vật phẩm','Trong kho cá nhân'],['Bộ sưu tập','2 / 6','Tiến độ minh họa']])}${tabs(['Tất cả','Giao diện','Hiệu ứng','Nền'])}<div class="grid">${['Mùa Xuân','Klain','Aether'].map((n,i)=>card(`<div class="art"><img src="../assets/Premium/Poster/${['xuan.png','Klain.png','aether.png'][i]}" alt="${n}"></div><span class="badge">${active==='Phần thưởng'?'NỀN ĐẶC BIỆT':'BỘ SƯU TẬP'}</span><h2 style="margin-top:12px">${n}</h2><p class="meta">${i===0?'Đã sở hữu':i===1?'Đủ điều kiện nhận thưởng':'Mở bán riêng sau khi chọn phần thưởng'}</p><details><summary>Vật phẩm cần thu thập</summary><p class="meta">Đã sở hữu 6/6 vật phẩm vĩnh viễn.</p></details><div class="actions">${btn(i===0?'Sử dụng nền':i===1?'Nhận phần thưởng':'Mua · 5.000 Coin')}</div>`)).join('')}</div>`;
if(active==='Giao bài tập'||active==='Ngân hàng câu hỏi')return card(`<h2>${active==='Giao bài tập'?'Thông tin bài tập':'Tạo câu hỏi mới'}</h2><div class="formgrid"><label>Tên bài<input placeholder="Ví dụ: Ôn tập chương 1"></label><label>Lớp nhận bài<select><option>Lớp 10A1</option></select></label><label class="wide">Nội dung<textarea placeholder="Nhập nội dung bài tập..."></textarea></label><label>Hạn nộp<input type="date"></label><label>Loại bài<select><option>Tự luận và trắc nghiệm</option></select></label><label class="wide">Đính kèm Video YouTube<input placeholder="Dán đường dẫn video..."></label><div class="wide"><span class="badge">Điều kiện video · 00 giờ 12 phút 30 giây</span><p class="meta">Thời lượng và điều kiện xem đặt cạnh nhau, dễ kiểm tra.</p></div></div><div class="actions">${btn('Lưu nháp','')}${btn('Giao bài tập')}</div>`);
if(active==='Lộ trình & lịch')return `${stats([['Tổng tiền tích lũy','2.000 đ','Chữ đậm rõ trên nền trắng'],['Tiến độ lộ trình','65%','Hoàn thành 13/20 bài'],['Lịch học tuần này','4 buổi','Buổi tiếp theo: Thứ tư']])}${tabs(['Lộ trình cá nhân','Thời khóa biểu'])}${card('<h2>Lộ trình tháng 10</h2><div class="progress"><b></b></div><p class="muted">Tiếp tục hoàn thành bài tập để tiến tới mục tiêu.</p>')}${table(['Ngày','Thời gian','Nội dung','Trạng thái'],[['Thứ hai','18:00 – 19:30','Ôn tập chương 1','Đã hoàn thành'],['Thứ tư','18:00 – 19:30','Luyện tập tổng hợp','Sắp diễn ra']])}`;
if(active.includes('trò chơi')||active==='Trò chơi')return `<div class="grid">${['Vòng quay may mắn','Hội họa','Điểm danh','Sự kiện theo mùa','Đại hội Trung thu','Lịch sử hào hùng'].map((n,i)=>card(`<div class="art">${['◎','✎','▦','✧','☾','⚑'][i]}</div><h2>${n}</h2><p class="meta">${role==='Giáo viên'?'Cấu hình điều kiện, lịch mở và phần thưởng.':'Khám phá hoạt động và nhận phần thưởng.'}</p>${btn(role==='Giáo viên'?'Quản lý':'Khám phá')}`)).join('')}</div>`;
if(active==='Quản lý phần thưởng')return `${card(`<h2>Công bố bộ thưởng</h2><div class="formgrid"><label>Vật phẩm cần sở hữu<select multiple><option>Vật phẩm 1 · Cửa hàng thường</option><option>Vật phẩm 2 · Cửa hàng sang trọng</option><option>Vật phẩm 3 · Cửa hàng sang trọng</option></select></label><label>Nền thưởng<select multiple><option>Nyx</option><option>Aether</option></select></label></div><p class="meta" style="margin-top:20px">Chọn nhiều nền: học sinh chọn một rồi bấm Nhận.</p>${btn('Công bố bộ thưởng')}`)}${table(['Bộ đã công bố','Điều kiện','Nền thưởng','Thao tác'],[['Mùa Xuân','6 vật phẩm','1 nền',btn('Sửa','')+' '+btn('Xóa','danger')],['Thần thoại','12 vật phẩm','Chọn 1 trong 2',btn('Sửa','')+' '+btn('Xóa','danger')]])}`;
if(active.includes('học sinh'))return `${toolbar('Tìm học sinh theo tên...')}${table(['Học sinh','Lớp','Số dư Coin','Trạng thái','Thao tác'],[['Nguyễn Minh An','10A1','8.500','Đang hoạt động',btn('Sửa','')+' '+btn('Xóa','danger')],['Trần Hà Linh','10A1','6.250','Đang hoạt động',btn('Sửa','')+' '+btn('Khóa','')]])}`;
if(active.includes('Thông báo')||active.includes('Hộp thư'))return `${tabs(['Thông báo','Khảo sát','Quà tặng'])}<div class="grid">${card('<span class="badge">MỚI</span><h2 style="margin-top:14px">Lịch học tuần mới</h2><p class="muted">Lớp sẽ bắt đầu lúc 18:00 thứ tư.</p>'+btn('Xem chi tiết',''))}${card('<h2>Khảo sát hoạt động</h2><p class="muted">Chọn hoạt động bạn muốn tham gia trong tháng.</p>'+btn('Mở khảo sát'))}</div>`;
if(active.includes('giao dịch')||active.includes('Giao dịch')||active==='Kháng cáo')return `${toolbar()}${table(['Nội dung','Học sinh','Thời gian','Trạng thái','Thao tác'],[['Yêu cầu '+(active==='Kháng cáo'?'xem lại điểm':'rút tiền'),'Nguyễn Minh An','01/10 · 09:30','Đang chờ',btn('Xem xét','')],['Hoàn thành bài tập','Trần Hà Linh','01/10 · 08:15','Đã hoàn tất',btn('Chi tiết','')]])}`;
if(active==='Bảng xếp hạng'||active==='Kết quả học tập')return `${stats([['Điểm trung bình','8,6','Tăng 0,4 so với tháng trước'],['Bài hoàn thành','18','Duy trì tiến độ tốt'],['Thứ hạng','03','Trong lớp 10A1']])}${table(['Bài học / học sinh','Điểm','Trạng thái','Chi tiết'],[['Ôn tập chương 1','9,0','Đạt',btn('Xem kết quả','')],['Luyện tập chương 2','8,5','Đạt',btn('Xem kết quả','')]])}`;
return `${stats([['Đang mở','06','Nội dung cần theo dõi'],['Đã hoàn thành','18','Trong tháng này'],['Cần chú ý','02','Sắp đến hạn']])}${toolbar(active==='Tài liệu học tập'?'Tìm tài liệu...':'Tìm bài tập...')}<div class="grid">${['Ôn tập chương 1','Luyện tập tổng hợp','Kiến thức nền tảng'].map((n,i)=>card(`<span class="badge ${i===1?'warning':''}">${active==='Tài liệu học tập'?'TÀI LIỆU PDF':i===1?'SẮP ĐẾN HẠN':'ĐANG MỞ'}</span><h2 style="margin-top:18px">${n}</h2><p class="meta">Lớp 10A1 · Cập nhật 01/10<br>${i+2} tệp đính kèm · Có video hướng dẫn</p><div class="actions">${btn('Xem chi tiết','')}${btn(role==='Giáo viên'?'Quản lý':active==='Tài liệu học tập'?'Mở tài liệu':'Làm bài')}</div>`)).join('')}</div>`;
}
function render(){document.querySelector('nav').innerHTML=menus[role].map((n,i)=>`<button class="${active===n?'active':''}" data-page="${n}"><i>${icons[i%icons.length]}</i><span>${n}</span></button>`).join('');document.querySelector('#rolename').textContent=role;document.querySelector('#breadcrumb').textContent='Lớp học / '+role;const screen=document.querySelector('#screen');screen.innerHTML=`<div class="titleline"><div><h1>${active}</h1><p class="subtitle">${role==='Giáo viên'?'Quản lý rõ ràng, thao tác nhất quán.':'Tập trung vào điều quan trọng hôm nay.'}</p></div>${role==='Giáo viên'?btn('＋ Thêm mới'):''}</div>`+content();screen.style.animation='none';void screen.offsetWidth;screen.style.animation='';}
document.querySelector('#role').onchange=e=>{role=e.target.value;active=menus[role][0];render()};document.querySelector('#motion').onclick=e=>{const off=document.body.classList.toggle('off');e.target.textContent='Chuyển động: '+(off?'Tắt':'Bật');render()};document.querySelector('#collapse').onclick=()=>document.querySelector('.shell').classList.toggle('collapsed');document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){active=p.dataset.page;render()}const d=e.target.closest('[data-dialog]');if(d){document.querySelector('#dialogtitle').textContent=d.dataset.dialog;document.querySelector('dialog').showModal()}if(e.target.id==='replay')render();if(e.target.matches('[data-tab]')){e.target.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active')}});document.querySelector('#cancel').onclick=document.querySelector('#accept').onclick=()=>document.querySelector('dialog').close();render();
